### ISSUE TITLE
entry module not found, have you add `import 'uno.css'` in your main entry?

### ISSUE THREAD

**Issue by liwenfengg** [zguolee/unocss-preset-uni#4]
uni-app in app mode
![QQ截图20220808112519](https://user-images.githubusercontent.com/40257198/183332290-93950e85-99e6-494d-b7ea-cc208a9b9971.png)

**Comment by zguolee** [comment]
Add uno.css to your main entry:
```
// main.ts
import 'uno.css'
```

**Comment by MellowCo** [comment]
> uni-app in app mode ![QQ截图20220808112519](https://user-images.githubusercontent.com/40257198/183332290-93950e85-99e6-494d-b7ea-cc208a9b9971.png)

see this https://github.com/MellowCo/unocss-preset-weapp#uniapp-vue3-vite-app%E6%89%93%E5%8C%85%E4%B8%AD%E6%96%AD

**Comment by MellowCo** [comment]
> > uni-app in app mode ![QQ截图20220808112519](https://user-images.githubusercontent.com/40257198/183332290-93950e85-99e6-494d-b7ea-cc208a9b9971.png)
> 
> see this https://github.com/MellowCo/unocss-preset-weapp#uniapp-vue3-vite-app%E6%89%93%E5%8C%85%E4%B8%AD%E6%96%AD

原来是uniapp打包app时，打包了2次，加上模式判断就行了
// app打包配置
// uniapp打包app时，打包2次，一次使用 vue 模式打包h5，第2次使用 nvue 模式打包app，
// 第2次打包 unocss 会抛出warn
// entry module not found, have you add `import 'uno.css'` in your main entry?
// 导致打包终止
process.env.UNI_COMPILER === 'vue' ? Unocss() : undefined,

**Comment by liwenfengg** [comment]
process.env.UNI_COMPILER === 'vue' ? Unocss() : undefined,这样设置后 h5 就不行了 export default ({ command, mode }: ConfigEnv): UserConfigExport => {  const env = loadEnv(mode, process.cwd())  log(colors.green('command        '), command)  log(colors.green('mode           '), mode)  log(colors.green('env            '), env)  log(colors.green('process.env.UNI_COMPILER'), process.env.UNI_COMPILER)  return defineConfig({    resolve: {      alias: {        '~/': `${path.resolve(__dirname, 'src')}/`,      },    },    plugins: [(command === 'serve' || (command === 'build' && process.env.UNI_COMPILER === 'vue')) ? Unocss() : undefined,我暂时时这样解决的Aug 10, 20224:16 PM，MellowCo ***@***.***> 写道：uni-app in app mode see this https://github.com/MellowCo/unocss-preset-weapp#uniapp-vue3-vite-app%E6%89%93%E5%8C%85%E4%B8%AD%E6%96%AD原来是uniapp打包app时，打包了2次，加上模式判断就行了 // app打包配置 // uniapp打包app时，打包2次，一次使用 vue 模式打包h5，第2次使用 nvue 模式打包app， // 第2次打包 unocss 会抛出warn // entry module not found, have you add import 'uno.css' in your main entry? // 导致打包终止 process.env.UNI_COMPILER === 'vue' ? Unocss() : undefined,—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by MellowCo** [comment]
> > > uni-app in app mode ![QQ截图20220808112519](https://user-images.githubusercontent.com/40257198/183332290-93950e85-99e6-494d-b7ea-cc208a9b9971.png) > > > see this https://github.com/MellowCo/unocss-preset-weapp#uniapp-vue3-vite-app%E6%89%93%E5%8C%85%E4%B8%AD%E6%96%AD 原来是uniapp打包app时，打包了2次，加上模式判断就行了 // app打包配置 // uniapp打包app时，打包2次，一次使用 vue 模式打包h5，第2次使用 nvue 模式打包app， // 第2次打包 unocss 会抛出warn // entry module not found, have you add `import 'uno.css'` in your main entry? // 导致打包终止 process.env.UNI_COMPILER === 'vue' ? Unocss() : undefined,
> process.env.UNI_COMPILER === 'vue' ? Unocss() : undefined, // 这样设置后 h5 就不行了  export default ({ command, mode }: ConfigEnv): UserConfigExport => { const env = loadEnv(mode, process.cwd()) log(colors.green('command '), command) log(colors.green('mode '), mode) log(colors.green('env '), env) log(colors.green('process.env.UNI_COMPILER'), process.env.UNI_COMPILER) return defineConfig({ resolve: { alias: { '~/': `${path.resolve(__dirname, 'src')}/`, }, }, plugins: [ (command === 'serve' || (command === 'build' && process.env.UNI_COMPILER === 'vue')) ? Unocss() : undefined, // 我暂时时这样解决的

改成这样就行了
```js
// app打包配置
// uniapp打包app时，打包2次，一次使用 vue 模式打包h5，第2次使用 nvue 模式打包app，
// 第2次打包 unocss 会抛出warn，导致打包终止
process.env.UNI_COMPILER !== 'nvue' ? Unocss() : undefined,
```

**Comment by liwenfengg** [comment]
> > > > uni-app in app mode ![QQ截图20220808112519](https://user-images.githubusercontent.com/40257198/183332290-93950e85-99e6-494d-b7ea-cc208a9b9971.png) > > > see this https://github.com/MellowCo/unocss-preset-weapp#uniapp-vue3-vite-app%E6%89%93%E5%8C%85%E4%B8%AD%E6%96%AD 原来是uniapp打包app时，打包了2次，加上模式判断就行了 // app打包配置 // uniapp打包app时，打包2次，一次使用 vue 模式打包h5，第2次使用 nvue 模式打包app， // 第2次打包 unocss 会抛出warn // entry module not found, have you add `import 'uno.css'` in your main entry? // 导致打包终止 process.env.UNI_COMPILER === 'vue' ? Unocss() : undefined,
> > > > process.env.UNI_COMPILER === 'vue' ? Unocss() : undefined, // 这样设置后 h5 就不行了  export default ({ command, mode }: ConfigEnv): UserConfigExport => { const env = loadEnv(mode, process.cwd()) log(colors.green('command '), command) log(colors.green('mode '), mode) log(colors.green('env '), env) log(colors.green('process.env.UNI_COMPILER'), process.env.UNI_COMPILER) return defineConfig({ resolve: { alias: { '~/': `${path.resolve(__dirname, 'src')}/`, }, }, plugins: [ (command === 'serve' || (command === 'build' && process.env.UNI_COMPILER === 'vue')) ? Unocss() : undefined, // 我暂时时这样解决的
> 
> 改成这样就行了
> 
> ```js
> // app打包配置
> // uniapp打包app时，打包2次，一次使用 vue 模式打包h5，第2次使用 nvue 模式打包app，
> // 第2次打包 unocss 会抛出warn，导致打包终止
> process.env.UNI_COMPILER !== 'nvue' ? Unocss() : undefined,
> ```

好的,谢谢你
