### ISSUE TITLE
What's the difference between unocss-preset-uni and unocss-preset-weapp?

### ISSUE THREAD

**Issue by liwenfengg** [zguolee/unocss-preset-uni#5]
https://github.com/zguolee/unocss-preset-uni
https://github.com/MellowCo/unocss-preset-weapp

**Comment by liwenfengg** [comment]
So if I use uni-app' to develop `app' and only use `unocss-preset-uni', is it enough?On the other hand, when I use `UnoCSS-preset-uni' and `UnoCSS-preset-WEAPP' in the project at the same time, some `UnoCSS' won't take effect (such as bg-[#ccc]), but it is normal when I remove `UnoCSS-preset-WEAPP'Aug 11, 20229:07 PM，Neil Lee ***@***.***> 写道：unocss-preset-uni only support uni-app and WeChat, QQ mini-program, unocss-preset-weapp support more and has a lot of customization, you can contact @MellowCo to get more information.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by zguolee** [comment]
Not recommended for not testing(In the issue #4, the `unocss-preset-weapp` author [@MellowCo](https://github.com/MellowCo) gives a solution to build app). The reason why using `unocss-preset-uni` and `unocss-preset-weapp` at the same time has no effect may be that some conversion rules or preset import order is different.

**Comment by MellowCo** [comment]
[unocss-preset-weapp](https://github.com/MellowCo/unocss-preset-weapp) 是基于 [@unocss/preset-mini](https://github.com/unocss/unocss/tree/main/packages/preset-mini) 修改的，为了满足小程序，将默认单位 `rem` 改为 `rpx` ，并修改了一些预设。

[unocss-preset-uni](https://github.com/zguolee/unocss-preset-uni) 是基于 [@unocss/preset-wind](https://github.com/unocss/unocss/tree/main/packages/preset-wind) 修改的

在对转义类名的处理上，`unocss-preset-weapp`  和 `unocss-preset-uni` 转换规则是不同的，所以会导致 `bg-[#ccc]` 失效

`unocss-preset-weapp` -> bg--fl--w-ccc-rl- [unplugin-transform-we-class](https://github.com/MellowCo/unplugin-transform-we-class#%E8%BD%AC%E6%8D%A2%E8%A7%84%E5%88%99)

`unocss-preset-uni` -> bg-l--h-ccc-r  [css-selector-transform](https://github.com/zguolee/unocss-preset-uni#css-selector-transform)

[unplugin-transform-we-class](https://github.com/MellowCo/unplugin-transform-we-class#%E8%BD%AC%E6%8D%A2%E8%A7%84%E5%88%99) 是用 [unplugin](https://github.com/unjs/unplugin) 作为插件入口，所以可以同时兼容 `webpack` 和 `vite` , uniapp vue2 , taro 都能使用

在 uniapp vue3 vite上，两个都是够用的

**Comment by liwenfengg** [comment]
好滴,我了解了,谢谢你 @MellowCo  以及 @zguolee
