### ISSUE TITLE
Background-image Arbitrary values don't work.

### ISSUE THREAD

**Issue by liwenfengg** [zguolee/unocss-preset-uni#7]
![image](https://user-images.githubusercontent.com/40257198/184612388-c49fa90b-5849-4af2-ba47-a5c0c4b56561.png)

https://tailwindcss.com/docs/background-image#arbitrary-values

**Comment by zguolee** [comment]
There are many problems in this `unocss-preset-uni` and may not be maintained in the future. Maybe you can use this one [unocss-applet](https://github.com/unocss-applet/unocss-applet). Welcome to join us.
